### ISSUE TITLE
migrate to the new version of flutter

### ISSUE THREAD

**Issue by noaman813** [iamSahdeep/fu_uber#3]
please give this awsome work a migration

**Comment by iamSahdeep** [comment]
Sure, but I have to look into things, maps migration and everything. Would take a bit of time.

**Comment by noaman813** [comment]
we are waiting <3

**Comment by iamSahdeep** [comment]
Probably this week. Just recovered from covid.🤦

**Comment by noaman813** [comment]
I wish you a speedy recovery and be good always.

**Comment by iamSahdeep** [comment]
Created new branch with everything updated. 
https://github.com/iamSahdeep/fu_uber/tree/nullsafe

Will soon move to master after some testing.

**Comment by noaman813** [comment]
ok, we are waiting for it. good job from you ✌❤
